"""
CRUD operations for the golf planner MongoDB database.

All functions accept a Motor AsyncIOMotorDatabase instance that is obtained
via FastAPI's dependency-injection system (app.database.get_database).
"""

import random
import re
import uuid
from datetime import datetime, timezone
from typing import Any, Dict, List, Optional

from motor.motor_asyncio import AsyncIOMotorDatabase

# Matches placeholder names generated by document_generator.generate_schedule()
# e.g. "Player 1", "Player 12"
_PLACEHOLDER_RE = re.compile(r"^Player \d+$")


# ═══════════════════════════════════════════════════════════════════════════
# Tournaments
# ═══════════════════════════════════════════════════════════════════════════


async def create_tournament(
    db: AsyncIOMotorDatabase,
    tournament_data: Dict[str, Any],
    schedule: List[Dict[str, Any]],
    brochure: Dict[str, Any],
    user_id: str = "",
) -> Dict[str, str]:
    """
    Persist a new tournament document and return its IDs.

    The registration_token is a UUID embedded in the public sign-up URL.
    """
    tournament_id = str(uuid.uuid4())
    registration_token = str(uuid.uuid4())

    doc = {
        "tournament_id": tournament_id,
        "name": tournament_data.get("name", ""),
        "date": tournament_data.get("date", ""),
        "venue": tournament_data.get("venue", ""),
        "format": tournament_data.get("format", ""),
        "number_of_days": int(tournament_data.get("numberOfDays") or 1),
        "player_count": int(tournament_data.get("playerCount", 0)),
        "event_type": tournament_data.get("eventType", ""),
        "team_size": int(tournament_data.get("teamSize") or 1),
        "registration_deadline": tournament_data.get("registrationDeadline", ""),
        "entry_fee": int(tournament_data.get("entryFee") or 0),
        "description": tournament_data.get("description", ""),
        "tee_time_start": tournament_data.get("teeTimeStart", "08:00"),
        "tee_time_interval": int(tournament_data.get("teeTimeInterval", 12)),
        "schedule": schedule,
        "brochure_subject": brochure.get("subject", ""),
        "brochure_body": brochure.get("body", ""),
        "registration_token": registration_token,
        "brochure_recipients": [],
        "status": "pending",
        "user_id": user_id,
        "created_at": datetime.now(timezone.utc),
        "original_tournament": tournament_data,
    }

    await db.tournaments.insert_one(doc)
    return {"tournament_id": tournament_id, "registration_token": registration_token}


async def get_tournament(
    db: AsyncIOMotorDatabase, tournament_id: str
) -> Optional[Dict[str, Any]]:
    """Return a tournament document by its UUID string (excludes MongoDB _id)."""
    return await db.tournaments.find_one(
        {"tournament_id": tournament_id}, {"_id": 0}
    )


async def get_tournament_by_token(
    db: AsyncIOMotorDatabase, token: str
) -> Optional[Dict[str, Any]]:
    """Return a tournament document by its registration token."""
    return await db.tournaments.find_one(
        {"registration_token": token}, {"_id": 0}
    )


async def list_tournaments(
    db: AsyncIOMotorDatabase, user_id: str = ""
) -> List[Dict[str, Any]]:
    """Return tournaments for a specific user, newest first, without MongoDB _id."""
    query = {"user_id": user_id} if user_id else {}
    cursor = db.tournaments.find(query, {"_id": 0}).sort("created_at", -1)
    return await cursor.to_list(length=None)


async def _update_schedule(
    db: AsyncIOMotorDatabase, tournament_id: str, schedule: List[Dict[str, Any]]
) -> bool:
    result = await db.tournaments.update_one(
        {"tournament_id": tournament_id},
        {"$set": {"schedule": schedule}},
    )
    return result.modified_count > 0


async def shuffle_schedule(
    db: AsyncIOMotorDatabase, tournament_id: str
) -> Optional[List[Dict[str, Any]]]:
    """
    Randomly redistribute all player names and placeholders across the
    existing groups while keeping tee times fixed.

    Returns the updated schedule, or None if the tournament wasn't found.
    """
    doc = await get_tournament(db, tournament_id)
    if doc is None:
        return None

    schedule: List[Dict[str, Any]] = doc["schedule"]

    # Collect every player entry in slot order then shuffle
    all_players: List[str] = [
        player for group in schedule for player in group["players"]
    ]
    random.shuffle(all_players)

    # Redistribute back, preserving group metadata (teeTime, group number)
    new_schedule: List[Dict[str, Any]] = []
    idx = 0
    for group in schedule:
        size = len(group["players"])
        new_schedule.append({**group, "players": all_players[idx : idx + size]})
        idx += size

    await _update_schedule(db, tournament_id, new_schedule)
    return new_schedule


async def update_brochure_recipients(
    db: AsyncIOMotorDatabase, tournament_id: str, emails: List[str]
) -> bool:
    result = await db.tournaments.update_one(
        {"tournament_id": tournament_id},
        {"$set": {"brochure_recipients": emails}},
    )
    return result.modified_count > 0


async def finalize_tournament(
    db: AsyncIOMotorDatabase, tournament_id: str
) -> bool:
    result = await db.tournaments.update_one(
        {"tournament_id": tournament_id},
        {"$set": {"status": "finalized"}},
    )
    return result.modified_count > 0


async def delete_tournament(
    db: AsyncIOMotorDatabase, tournament_id: str
) -> bool:
    """Delete the tournament and all associated registration records."""
    await db.registrations.delete_many({"tournament_id": tournament_id})
    result = await db.tournaments.delete_one({"tournament_id": tournament_id})
    return result.deleted_count > 0


# ═══════════════════════════════════════════════════════════════════════════
# Registrations
# ═══════════════════════════════════════════════════════════════════════════


async def count_registrations(
    db: AsyncIOMotorDatabase, tournament_id: str
) -> int:
    return await db.registrations.count_documents({"tournament_id": tournament_id})


async def get_registrations(
    db: AsyncIOMotorDatabase, tournament_id: str
) -> List[Dict[str, Any]]:
    cursor = db.registrations.find(
        {"tournament_id": tournament_id},
        {"_id": 0},
    ).sort("registered_at", 1)
    return await cursor.to_list(length=None)


async def register_player(
    db: AsyncIOMotorDatabase,
    tournament_id: str,
    first_name: str,
    last_name: str,
) -> Optional[Dict[str, Any]]:
    """
    Claim the next available placeholder slot in the schedule for a player.

    Scans schedule groups in order and replaces the first string that matches
    the placeholder pattern ("Player N") with the player's full name.

    Returns a dict with registration details, or None if the tournament is
    full / not found.
    """
    doc = await get_tournament(db, tournament_id)
    if doc is None or doc["status"] == "finalized":
        return None

    schedule: List[Dict[str, Any]] = doc["schedule"]
    full_name = f"{first_name} {last_name}"
    slot_description: Optional[str] = None
    found = False

    for group in schedule:
        for i, player in enumerate(group["players"]):
            if _PLACEHOLDER_RE.match(player):
                group["players"][i] = full_name
                slot_description = f"Group {group['group']} @ {group['teeTime']}"
                found = True
                break
        if found:
            break

    if not found:
        return None  # All slots are taken

    # Persist updated schedule
    await _update_schedule(db, tournament_id, schedule)

    # Audit log entry
    reg_doc = {
        "registration_id": str(uuid.uuid4()),
        "tournament_id": tournament_id,
        "first_name": first_name,
        "last_name": last_name,
        "registered_at": datetime.now(timezone.utc),
    }
    await db.registrations.insert_one(reg_doc)

    registered_count = await count_registrations(db, tournament_id)
    return {
        "success": True,
        "slot_description": slot_description,
        "players_registered": registered_count,
        "total_players": doc["player_count"],
    }
